### ISSUE TITLE
windows下波特率的问题

### ISSUE THREAD

**Issue by kerojiang** [xluohome/serial#1]
linux的代码里面有个波特率的map，里面是支持的波特率列表吧，windows下没有这个东西，我现在windows下测试，波特率为3000000的时候，读取的串口数据有点问题，是因为windows下不支持吗？

**Comment by xluohome** [comment]
&nbsp;普通的波特率譬如 ：9600 ， 是否可以？；&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xluohome/serial"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 上午10:09
收件人:&nbsp;"xluohome/serial"<serial@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xluohome/serial] windows下波特率的问题 (#1)





 
linux的代码里面有个波特率的map，里面是支持的波特率列表吧，windows下没有这个东西，我现在windows下测试，波特率为3000000的时候，读取的串口数据有点问题，是因为windows下不支持吗？

**Comment by kerojiang** [comment]
试了1000000波特率可以
